development:
  PORT:
  RACK_ENV:

  DATABASE_URL:
  DATABASE_NAME:
  DATABASE_HOST:
  DATABASE_PORT:
  DATABASE_POOL:
  DATABASE_USER:
  DATABASE_PASSWORD:

  REDIS_URL:
  REDIS_HOST:
  REDIS_PORT:

  DEVISE_SECRET_KEY:
  DEVISE_PEPPER:
  SECRET_KEY_BASE:

  S3_KEY:
  S3_SECRET:
  S3_BUCKET:
  S3_REGION:
